# Generated by Django 6.0.7 on 2026-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
