# Generated by Django 5.2.16 on 2026-07-31 05:25

import apps.jdimport.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0005_alter_job_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JDImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jd_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JDImportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=apps.jdimport.models.jd_upload_path),
                ),
                ("file_type", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("converting", "Converting"),
                            ("converted", "Converted"),
                            ("extracting", "Extracting"),
                            ("extracted", "Ready for Review"),
                            ("failed", "Failed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("markdown_text", models.TextField(blank=True)),
                ("extracted_json", models.JSONField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="jdimport.jdimportbatch",
                    ),
                ),
                (
                    "created_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_from",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
